name: Publish Package to npmjs

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 8
            - uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
                  registry-url: 'https://registry.npmjs.org'
                  cache: 'pnpm'
            - run: pnpm i --frozen-lockfile
            - run: pnpm build:sdk
            - name: Publish package on NPM 📦
              run: pnpm publish:sdk
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
